global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-app'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['flask-app:8000']  # Point to the /metrics path exposed by your Flask app
